"""auto_sync_1780668923

Revision ID: 32242c242eb2
Revises: 
Create Date: 2026-06-05 10:15:24.761585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32242c242eb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.String(length=100), nullable=True),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_bitacora_id'), 'bitacora', ['id'], unique=False, schema='public')
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_cliente_correo'), 'cliente', ['correo'], unique=True, schema='public')
    op.create_index(op.f('ix_public_cliente_id'), 'cliente', ['id'], unique=False, schema='public')
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_especialidad_id'), 'especialidad', ['id'], unique=False, schema='public')
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_estado_nombre'), 'estado', ['nombre'], unique=True, schema='public')
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='public'
    )
    op.create_index(op.f('ix_public_permiso_id'), 'permiso', ['id'], unique=False, schema='public')
    op.create_table('plan_suscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio_mensual', sa.Float(), nullable=True),
    sa.Column('max_sucursales', sa.Integer(), nullable=True),
    sa.Column('max_tecnicos', sa.Integer(), nullable=True),
    sa.Column('max_admins_sucursal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='public'
    )
    op.create_index(op.f('ix_public_plan_suscripcion_id'), 'plan_suscripcion', ['id'], unique=False, schema='public')
    op.create_table('prioridad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='public'
    )
    op.create_index(op.f('ix_public_rol_id'), 'rol', ['id'], unique=False, schema='public')
    op.create_table('categoria_problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('idEspecialidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEspecialidad'], ['public.especialidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('ultimo4', sa.String(length=4), nullable=True),
    sa.Column('es_predeterminado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['public.cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_metodo_pago_id'), 'metodo_pago', ['id'], unique=False, schema='public')
    op.create_table('plan_permiso',
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['public.permiso.id'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['public.plan_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id_plan', 'id_permiso'),
    schema='public'
    )
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['public.permiso.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['public.rol.id'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso'),
    schema='public'
    )
    op.create_table('taller',
    sa.Column('cod', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('calificacion_promedio', sa.Float(), server_default='5.0', nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['public.usuario.id'], name='fk_taller_admin', use_alter=True),
    sa.ForeignKeyConstraint(['plan_id'], ['public.plan_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('cod'),
    schema='public'
    )
    op.create_index(op.f('ix_public_taller_cod'), 'taller', ['cod'], unique=False, schema='public')
    op.create_table('vehiculo',
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['public.cliente.id'], ),
    sa.PrimaryKeyConstraint('placa'),
    schema='public'
    )
    op.create_index(op.f('ix_public_vehiculo_idCliente'), 'vehiculo', ['idCliente'], unique=False, schema='public')
    op.create_index(op.f('ix_public_vehiculo_placa'), 'vehiculo', ['placa'], unique=False, schema='public')
    op.create_table('asignacion_especialidad',
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.Column('idEspecialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEspecialidad'], ['public.especialidad.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['public.taller.cod'], ),
    sa.PrimaryKeyConstraint('idTaller', 'idEspecialidad'),
    schema='public'
    )
    op.create_table('emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('textoAdicional', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('es_valida', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=True),
    sa.Column('idPrioridad', sa.Integer(), nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('placaVehiculo', sa.String(length=20), nullable=False),
    sa.Column('idEstado', sa.Integer(), server_default='1', nullable=False),
    sa.Column('locked_by', sa.String(length=10), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['public.categoria_problema.id'], ),
    sa.ForeignKeyConstraint(['idCliente'], ['public.cliente.id'], ),
    sa.ForeignKeyConstraint(['idEstado'], ['public.estado.id'], ),
    sa.ForeignKeyConstraint(['idPrioridad'], ['public.prioridad.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['public.taller.cod'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['public.taller.cod'], ),
    sa.ForeignKeyConstraint(['placaVehiculo'], ['public.vehiculo.placa'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_emergencia_id'), 'emergencia', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_emergencia_idCliente'), 'emergencia', ['idCliente'], unique=False, schema='public')
    op.create_index(op.f('ix_public_emergencia_idEstado'), 'emergencia', ['idEstado'], unique=False, schema='public')
    op.create_index(op.f('ix_public_emergencia_idTaller'), 'emergencia', ['idTaller'], unique=False, schema='public')
    op.create_index(op.f('ix_public_emergencia_placaVehiculo'), 'emergencia', ['placaVehiculo'], unique=False, schema='public')
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['public.taller.cod'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sucursal_id'), 'sucursal', ['id'], unique=False, schema='public')
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.Column('descripcion_servicio', sa.Text(), nullable=False),
    sa.Column('costo_mano_obra', sa.Float(), nullable=False),
    sa.Column('costo_repuestos', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado_horas', sa.Integer(), nullable=False),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['public.emergencia.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['public.taller.cod'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_cotizacion_id'), 'cotizacion', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_cotizacion_idEmergencia'), 'cotizacion', ['idEmergencia'], unique=False, schema='public')
    op.create_index(op.f('ix_public_cotizacion_idTaller'), 'cotizacion', ['idTaller'], unique=False, schema='public')
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['public.emergencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_evidencia_idEmergencia'), 'evidencia', ['idEmergencia'], unique=False, schema='public')
    op.create_table('historial_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaCambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.Column('idEstado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['public.emergencia.id'], ),
    sa.ForeignKeyConstraint(['idEstado'], ['public.estado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_historial_estado_idEmergencia'), 'historial_estado', ['idEmergencia'], unique=False, schema='public')
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('rol_remitente', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEmergencia'], ['public.emergencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_mensajes_chat_id'), 'mensajes_chat', ['id'], unique=False, schema='public')
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('MontoComision', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stripe_intent_id', sa.String(length=255), nullable=True),
    sa.Column('metodo_pago_id', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), server_default='PENDIENTE', nullable=False),
    sa.Column('detalle_factura', sa.JSON(), nullable=True),
    sa.Column('fechaPago', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['public.cliente.id'], ),
    sa.ForeignKeyConstraint(['emergencia_id'], ['public.emergencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_pago_id'), 'pago', ['id'], unique=False, schema='public')
    op.create_table('resumen_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Resumen', sa.Text(), nullable=False),
    sa.Column('FichaTecnica', sa.JSON(), nullable=True),
    sa.Column('recomendaciones_taller', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['public.emergencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_resumen_ia_idEmergencia'), 'resumen_ia', ['idEmergencia'], unique=False, schema='public')
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idSucursal'], ['public.sucursal.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['public.taller.cod'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tecnico_correo'), 'tecnico', ['correo'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tecnico_id'), 'tecnico', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tecnico_idSucursal'), 'tecnico', ['idSucursal'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tecnico_idTaller'), 'tecnico', ['idTaller'], unique=False, schema='public')
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idSucursal'], ['public.sucursal.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['public.taller.cod'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_usuario_correo'), 'usuario', ['correo'], unique=True, schema='public')
    op.create_index(op.f('ix_public_usuario_id'), 'usuario', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_usuario_idSucursal'), 'usuario', ['idSucursal'], unique=False, schema='public')
    op.create_index(op.f('ix_public_usuario_idTaller'), 'usuario', ['idTaller'], unique=False, schema='public')
    op.create_table('asignacion_tecnico_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idTecnico', sa.Integer(), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['public.emergencia.id'], ),
    sa.ForeignKeyConstraint(['idTecnico'], ['public.tecnico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_asignacion_tecnico_emergencia_idEmergencia'), 'asignacion_tecnico_emergencia', ['idEmergencia'], unique=False, schema='public')
    op.create_index(op.f('ix_public_asignacion_tecnico_emergencia_idTecnico'), 'asignacion_tecnico_emergencia', ['idTecnico'], unique=False, schema='public')
    op.create_table('fcm_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('dispositivo', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idCliente'], ['public.cliente.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['public.usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='public'
    )
    op.create_index(op.f('ix_public_fcm_token_id'), 'fcm_token', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_fcm_token_idCliente'), 'fcm_token', ['idCliente'], unique=False, schema='public')
    op.create_index(op.f('ix_public_fcm_token_idUsuario'), 'fcm_token', ['idUsuario'], unique=False, schema='public')
    op.create_table('tecnico_especialidad',
    sa.Column('idTecnico', sa.Integer(), nullable=False),
    sa.Column('idEspecialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEspecialidad'], ['public.especialidad.id'], ),
    sa.ForeignKeyConstraint(['idTecnico'], ['public.tecnico.id'], ),
    sa.PrimaryKeyConstraint('idTecnico', 'idEspecialidad'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnico_especialidad', schema='public')
    op.drop_index(op.f('ix_public_fcm_token_idUsuario'), table_name='fcm_token', schema='public')
    op.drop_index(op.f('ix_public_fcm_token_idCliente'), table_name='fcm_token', schema='public')
    op.drop_index(op.f('ix_public_fcm_token_id'), table_name='fcm_token', schema='public')
    op.drop_table('fcm_token', schema='public')
    op.drop_index(op.f('ix_public_asignacion_tecnico_emergencia_idTecnico'), table_name='asignacion_tecnico_emergencia', schema='public')
    op.drop_index(op.f('ix_public_asignacion_tecnico_emergencia_idEmergencia'), table_name='asignacion_tecnico_emergencia', schema='public')
    op.drop_table('asignacion_tecnico_emergencia', schema='public')
    op.drop_index(op.f('ix_public_usuario_idTaller'), table_name='usuario', schema='public')
    op.drop_index(op.f('ix_public_usuario_idSucursal'), table_name='usuario', schema='public')
    op.drop_index(op.f('ix_public_usuario_id'), table_name='usuario', schema='public')
    op.drop_index(op.f('ix_public_usuario_correo'), table_name='usuario', schema='public')
    op.drop_table('usuario', schema='public')
    op.drop_index(op.f('ix_public_tecnico_idTaller'), table_name='tecnico', schema='public')
    op.drop_index(op.f('ix_public_tecnico_idSucursal'), table_name='tecnico', schema='public')
    op.drop_index(op.f('ix_public_tecnico_id'), table_name='tecnico', schema='public')
    op.drop_index(op.f('ix_public_tecnico_correo'), table_name='tecnico', schema='public')
    op.drop_table('tecnico', schema='public')
    op.drop_index(op.f('ix_public_resumen_ia_idEmergencia'), table_name='resumen_ia', schema='public')
    op.drop_table('resumen_ia', schema='public')
    op.drop_index(op.f('ix_public_pago_id'), table_name='pago', schema='public')
    op.drop_table('pago', schema='public')
    op.drop_index(op.f('ix_public_mensajes_chat_id'), table_name='mensajes_chat', schema='public')
    op.drop_table('mensajes_chat', schema='public')
    op.drop_index(op.f('ix_public_historial_estado_idEmergencia'), table_name='historial_estado', schema='public')
    op.drop_table('historial_estado', schema='public')
    op.drop_index(op.f('ix_public_evidencia_idEmergencia'), table_name='evidencia', schema='public')
    op.drop_table('evidencia', schema='public')
    op.drop_index(op.f('ix_public_cotizacion_idTaller'), table_name='cotizacion', schema='public')
    op.drop_index(op.f('ix_public_cotizacion_idEmergencia'), table_name='cotizacion', schema='public')
    op.drop_index(op.f('ix_public_cotizacion_id'), table_name='cotizacion', schema='public')
    op.drop_table('cotizacion', schema='public')
    op.drop_index(op.f('ix_public_sucursal_id'), table_name='sucursal', schema='public')
    op.drop_table('sucursal', schema='public')
    op.drop_index(op.f('ix_public_emergencia_placaVehiculo'), table_name='emergencia', schema='public')
    op.drop_index(op.f('ix_public_emergencia_idTaller'), table_name='emergencia', schema='public')
    op.drop_index(op.f('ix_public_emergencia_idEstado'), table_name='emergencia', schema='public')
    op.drop_index(op.f('ix_public_emergencia_idCliente'), table_name='emergencia', schema='public')
    op.drop_index(op.f('ix_public_emergencia_id'), table_name='emergencia', schema='public')
    op.drop_table('emergencia', schema='public')
    op.drop_table('asignacion_especialidad', schema='public')
    op.drop_index(op.f('ix_public_vehiculo_placa'), table_name='vehiculo', schema='public')
    op.drop_index(op.f('ix_public_vehiculo_idCliente'), table_name='vehiculo', schema='public')
    op.drop_table('vehiculo', schema='public')
    op.drop_index(op.f('ix_public_taller_cod'), table_name='taller', schema='public')
    op.drop_table('taller', schema='public')
    op.drop_table('rol_permiso', schema='public')
    op.drop_table('plan_permiso', schema='public')
    op.drop_index(op.f('ix_public_metodo_pago_id'), table_name='metodo_pago', schema='public')
    op.drop_table('metodo_pago', schema='public')
    op.drop_table('categoria_problema', schema='public')
    op.drop_index(op.f('ix_public_rol_id'), table_name='rol', schema='public')
    op.drop_table('rol', schema='public')
    op.drop_table('prioridad', schema='public')
    op.drop_index(op.f('ix_public_plan_suscripcion_id'), table_name='plan_suscripcion', schema='public')
    op.drop_table('plan_suscripcion', schema='public')
    op.drop_index(op.f('ix_public_permiso_id'), table_name='permiso', schema='public')
    op.drop_table('permiso', schema='public')
    op.drop_index(op.f('ix_public_estado_nombre'), table_name='estado', schema='public')
    op.drop_table('estado', schema='public')
    op.drop_index(op.f('ix_public_especialidad_id'), table_name='especialidad', schema='public')
    op.drop_table('especialidad', schema='public')
    op.drop_index(op.f('ix_public_cliente_id'), table_name='cliente', schema='public')
    op.drop_index(op.f('ix_public_cliente_correo'), table_name='cliente', schema='public')
    op.drop_table('cliente', schema='public')
    op.drop_index(op.f('ix_public_bitacora_id'), table_name='bitacora', schema='public')
    op.drop_table('bitacora', schema='public')
    # ### end Alembic commands ###
