"""Add calificacion_promedio

Revision ID: 66f675a521e4
Revises: 9d006d7868fc
Create Date: 2026-05-29 22:18:26.161318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f675a521e4'
down_revision: Union[str, None] = '9d006d7868fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taller', sa.Column('calificacion_promedio', sa.Float(), server_default='5.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taller', 'calificacion_promedio')
    # ### end Alembic commands ###
