"""Add Cotizacion model

Revision ID: 9d006d7868fc
Revises: f54e1430b720
Create Date: 2026-05-29 21:44:58.476136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d006d7868fc'
down_revision: Union[str, None] = 'f54e1430b720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.Column('descripcion_servicio', sa.Text(), nullable=False),
    sa.Column('costo_mano_obra', sa.Float(), nullable=False),
    sa.Column('costo_repuestos', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado_horas', sa.Integer(), nullable=False),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['emergencia.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['taller.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizacion_id'), 'cotizacion', ['id'], unique=False)
    op.create_index(op.f('ix_cotizacion_idEmergencia'), 'cotizacion', ['idEmergencia'], unique=False)
    op.create_index(op.f('ix_cotizacion_idTaller'), 'cotizacion', ['idTaller'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotizacion_idTaller'), table_name='cotizacion')
    op.drop_index(op.f('ix_cotizacion_idEmergencia'), table_name='cotizacion')
    op.drop_index(op.f('ix_cotizacion_id'), table_name='cotizacion')
    op.drop_table('cotizacion')
    # ### end Alembic commands ###
