"""cotizacion_detallada

Revision ID: c01e7f67bd97
Revises: a851b0d2d390
Create Date: 2026-06-07 17:52:31.040170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01e7f67bd97'
down_revision: Union[str, None] = 'a851b0d2d390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('moneda', sa.String(length=3), server_default='BOB', nullable=False))
    op.add_column('cotizacion', sa.Column('lista_productos', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('cotizacion', sa.Column('lista_servicios', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('cotizacion', sa.Column('subtotal_productos', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('cotizacion', sa.Column('subtotal_servicios', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('cotizacion', sa.Column('total_general', sa.Float(), server_default='0.0', nullable=False))
    op.alter_column('cotizacion', 'descripcion_servicio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('cotizacion', 'costo_mano_obra')
    op.drop_column('cotizacion', 'costo_repuestos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('costo_repuestos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cotizacion', sa.Column('costo_mano_obra', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, server_default='0.0'))
    op.alter_column('cotizacion', 'descripcion_servicio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('cotizacion', 'total_general')
    op.drop_column('cotizacion', 'subtotal_servicios')
    op.drop_column('cotizacion', 'subtotal_productos')
    op.drop_column('cotizacion', 'lista_servicios')
    op.drop_column('cotizacion', 'lista_productos')
    op.drop_column('cotizacion', 'moneda')
    # ### end Alembic commands ###
