"""Make idTaller nullable

Revision ID: e9760ffa9540
Revises: d952a66dfad4
Create Date: 2026-06-05 19:07:21.768339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9760ffa9540'
down_revision: Union[str, None] = 'd952a66dfad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'idTaller',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'idTaller',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='public')
    # ### end Alembic commands ###
