"""auto_sync_1780080879

Revision ID: f54e1430b720
Revises: 3f39f904cbcc
Create Date: 2026-05-29 14:54:40.749463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54e1430b720'
down_revision: Union[str, None] = '3f39f904cbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bitacora_idUsuario_fkey'), 'bitacora', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('bitacora_idUsuario_fkey'), 'bitacora', 'usuario', ['idUsuario'], ['id'])
    # ### end Alembic commands ###
